<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.vaadin.componentfactory</groupId>
    <artifactId>vaadin-liferay-portlet-parent</artifactId>
    <name>Vaadin Liferay Portlet support</name>
    <packaging>pom</packaging>
    <version>4.0.0-SNAPSHOT</version>

    <modules>
        <module>vaadin-portlet-cdi</module>
        <!-- Pluto Java 11 compatibility is coming perhaps December 2022 -->
        <!-- see https://www.mail-archive.com/pluto-dev@portals.apache.org/msg05719.html -->
        <!-- and https://github.com/vaadin/portlet/issues/226-->
<!--    <module>vaadin-portlet-integration-tests</module>-->
        <module>vaadin-portlet-liferay-integration-tests</module>
    </modules>

    <organization>
        <name>Vaadin Ltd</name>
        <url>http://vaadin.com</url>
    </organization>

    <url>https://vaadin.com/directory/</url>

    <licenses>
        <license>
            <name>Vaadin Commercial License and Service Terms</name>
            <url>https://vaadin.com/commercial-license-and-service-terms</url>
        </license>
    </licenses>

    <inceptionYear>2026</inceptionYear>

    <distributionManagement>
        <snapshotRepository>
            <id>vaadin-snapshots</id>
            <name>Vaadin snapshot repository</name>
            <url>http://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>vaadin-addons</id>
            <name>Vaadin add-ons repository</name>
            <url>http://tools.vaadin.com/nexus/content/repositories/vaadin-addons</url>
        </repository>
    </distributionManagement>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <jsinterop.version>1.0.1</jsinterop.version>
        <sonar.java.source>${java.version}</sonar.java.source>
        <sonar.analysis.mode>preview</sonar.analysis.mode>
        <sonar.issuesReport.console.enable>true
        </sonar.issuesReport.console.enable>
        <sonar.issuesReport.html.enable>true</sonar.issuesReport.html.enable>
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <failOnMissingWebXml>false</failOnMissingWebXml>

        <!-- Dependencies -->
        <slf4j.version>1.7.25</slf4j.version>

        <!-- Plugins -->
        <driver.binary.downloader.maven.plugin.version>1.0.14</driver.binary.downloader.maven.plugin.version>
        <frontend.maven.plugin.version>1.5</frontend.maven.plugin.version>
        <maven.surefire.plugin.version>2.22.2</maven.surefire.plugin.version>
        <maven.failsafe.plugin.version>2.22.2</maven.failsafe.plugin.version>

        <maven.war.plugin.version>3.1.0</maven.war.plugin.version>
        <maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
        <maven.resources.plugin.version>3.0.2</maven.resources.plugin.version>
        <maven.clean.plugin.version>3.0.0</maven.clean.plugin.version>

        <testbench.version>9.3.2</testbench.version>
        <vaadin.version>25.1.3</vaadin.version>
        <flow.version>25.1.3</flow.version>
        <flow.cdi.version>16.0.0</flow.cdi.version>
        <jetty.version>12.0.16</jetty.version>
        <jakarta.validation.version>3.0.0</jakarta.validation.version>
        <webdrivermanager.version>5.2.3</webdrivermanager.version>
        <vaadin-liferay-portlet-bridge.version>4.0.0-beta2</vaadin-liferay-portlet-bridge.version>

        <liferay.kernel.version>178.0.1</liferay.kernel.version>
        <deltaspike.version>1.8.1</deltaspike.version>

        <maven.test.skip>false</maven.test.skip>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>liferay-public</id>
            <name>Liferay Public</name>
            <url>https://repository.liferay.com/nexus/content/repositories/public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.vaadin.componentfactory</groupId>
                <artifactId>vaadin-liferay-portlet-bridge</artifactId>
                <version>${vaadin-liferay-portlet-bridge.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.11.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.13.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>1.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.jcip</groupId>
                <artifactId>jcip-annotations</artifactId>
                <version>1.0</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
            </plugin>

            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <version>0.1</version>
                <executions>
                    <execution>
                        <id>set-root-dir-for-common-lifecycle</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>initialize</phase>
                        <configuration>
                            <property>project.rootdir</property>
                        </configuration>
                    </execution>
                    <execution>
                        <id>set-root-dir-for-clean-lifecycle</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>pre-clean</phase>
                        <configuration>
                            <property>project.rootdir</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>${maven.clean.plugin.version}</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${project.basedir}/driver</directory>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/driver_zips</directory>
                        </fileset>
                        <fileset>
                            <directory>error-screenshots</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.0.2</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            </manifest>
                            <manifestEntries>
                                <CvdlName>vaadin-liferay-portlet-bridge</CvdlName>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.0.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>2.10.4</version>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <quiet>true</quiet>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>${maven.war.plugin.version}</version>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Implementation-Title>${project.name}</Implementation-Title>
                                <Implementation-Version>${project.version}</Implementation-Version>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven.failsafe.plugin.version}</version>
                    <configuration>
                        <trimStackTrace>false</trimStackTrace>
                        <enableAssertions>true</enableAssertions>
                        <parallel>all</parallel>
                        <threadCount>2</threadCount>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>com.sun.xml.bind</groupId>
                            <artifactId>jaxb-impl</artifactId>
                            <version>2.3.6</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>com.github.siom79.japicmp</groupId>
                    <artifactId>japicmp-maven-plugin</artifactId>
                    <dependencies>
                        <dependency>
                            <groupId>jakarta.activation</groupId>
                            <artifactId>jakarta.activation-api</artifactId>
                            <version>2.1.3</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>2.4.0</version>
                    <!--  Use `mvn license:update-file-header` to fix header problems -->
                    <configuration>
                        <licenseName>cval3</licenseName>
                        <licenseResolver>${project.baseUri}src/license</licenseResolver>
                        <includes>
                            <include>**/main/**/*.java</include>
                        </includes>
                        <failOnMissingHeader>true</failOnMissingHeader>
                        <failOnNotUptodateHeader>true</failOnNotUptodateHeader>
                    </configuration>
                    <executions>
                        <execution>
                            <id>license</id>
                            <phase>process-sources</phase>
                            <goals>
                                <goal>update-file-header</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
